# Generated by Django 3.2 on 2021-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('start_course', models.DateTimeField(auto_now_add=True)),
                ('end_course', models.DateTimeField(auto_now_add=True, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
