# Generated by Django 3.2 on 2021-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_course',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_course',
            field=models.DateTimeField(null=True),
        ),
    ]
